INSERT INTO category (ID, CTGRY_DSCRPTN) VALUES (1, 'American');
INSERT INTO category (ID, CTGRY_DSCRPTN) VALUES (2, 'Italian');
INSERT INTO category (ID, CTGRY_DSCRPTN) VALUES (3, 'Mexican');
INSERT INTO category (ID, CTGRY_DSCRPTN) VALUES (4, 'Fast Food');
INSERT INTO unit_of_measure (ID,UOM_DSCRPTN) VALUES (1,'Teaspoon');
INSERT INTO unit_of_measure (ID,UOM_DSCRPTN) VALUES (2, 'Tablespoon');
INSERT INTO unit_of_measure (ID,UOM_DSCRPTN) VALUES (3, 'Cup');
INSERT INTO unit_of_measure (ID,UOM_DSCRPTN) VALUES (4, 'Pinch');
INSERT INTO unit_of_measure (ID,UOM_DSCRPTN) VALUES (5, 'Ounce');
INSERT INTO unit_of_measure (ID,UOM_DSCRPTN) VALUES (6, 'Each');
INSERT INTO unit_of_measure (ID,UOM_DSCRPTN) VALUES (7, 'Dash');
INSERT INTO unit_of_measure (ID,UOM_DSCRPTN) VALUES (8, 'Pint');